export default {
  math: {
    AG: 'Algebraic Geometry',
    AT: 'Algebraic Topology',
    AP: 'Analysis of PDEs',
    CT: 'Category Theory',
    CA: 'Classical Analysis and ODEs',
    CO: 'Combinatorics',
    AC: 'Communicative Algebra',
    CV: 'Complex Variables',
    DG: 'Differential Geometry',
    DS: 'Dynamical Systems',
    FA: 'Functional Analysis',
    GM: 'General Math',
    GN: 'General Topology',
    GT: 'Geometric Topology',
    GR: 'Group Theory',
    HO: 'History and Overview',
    IT: 'Information Theory',
    KT: 'K-Theory and Homology',
    LO: 'Logic',
    MP: 'Mathematical Physics',
    MG: 'Metric Geometry',
    NT: 'Number Theory',
    NA: 'Numerical  Analysis',
    OA: 'Operator Algebras',
    OC: 'Optimization and Control',
    PR: 'Probability',
    QA: 'Quantum Algebra',
    RT: 'Representation Theory',
    RA: 'Rings and Algebra',
    SP: 'Spectral Theory',
    ST: 'Statistics Theory',
    SG: 'Symplectic Geometry'
  },
  physics: {
    'acc-ph': 'Accelerator Physics',
    'ao-ph': 'Atmospheric and Oceanic Physics',
    'atom-ph': 'Atomic Physics',
    'atm-clus': 'Atomic and Molecular Clusters',
    'bio-ph': 'Biological Physics',
    'chem-ph': 'Chemical Physics',
    'class-ph': 'Classical Physics',
    'comp-ph': 'Computational Physics',
    'data-an': 'Data Analysis, Statistics and Probability',
    'flu-dyn': 'Fluid Dynamics',
    'gen-ph': 'General Physics',
    'geo-ph': 'Geophysics',
    'hist-ph': 'History and Philosophy of Physics',
    'ins-det': 'Instrumentation and Detectors',
    'med-ph': 'Medical Physics',
    optics: 'Optics',
    'ed-ph': 'Physics Education',
    'soc-ph': 'Physics and Society',
    'plasm-ph': 'Plasma Physics',
    'pop-ph': 'Popular Physics',
    'space-ph': 'Space Physics'
  },
  stat: {
    AP: 'Applications',
    CO: 'Computation',
    ML: 'Machine Learning',
    ME: 'Methodology',
    OT: 'Other Statistics',
    TH: 'Statistics Theory'
  },
  'q-bio': {
    BM: 'Biomolecules',
    CB: 'Cell Behavior',
    GN: 'Genomics',
    MN: 'Molecular Networks',
    NC: 'Neurons and Cognition',
    OT: 'Other',
    PE: 'Populations and Evolution',
    QM: 'Quantitative Methods',
    SC: 'Subcellular Processes',
    TO: 'Tissues and Organs'
  },
  cs: {
    AR: 'Architecture',
    AI: 'Artificial Intelligence',
    CL: 'Computation and Language',
    CC: 'Computational Complexity',
    CE: 'Computational Engineering; Finance; and Science',
    CG: 'Computational Geometry',
    GT: 'Computer Science and Game Theory',
    CV: 'Computer Vision and Pattern Recognition',
    CY: 'Computers and Society',
    CR: 'Cryptography and Security',
    DS: 'Data Structures and Algorithms',
    DB: 'Databases',
    DL: 'Digital Libraries',
    DM: 'Discrete Mathematics',
    DC: 'Distributed; Parallel; and Cluster Computing',
    GL: 'General Literature',
    GR: 'Graphics',
    HC: 'Human-Computer Interaction',
    IR: 'Information Retrieval',
    IT: 'Information Theory',
    LG: 'Learning',
    LO: 'Logic in Computer Science',
    MS: 'Mathematical Software',
    MA: 'Multiagent Systems',
    MM: 'Multimedia',
    NI: 'Networking and Internet Architecture',
    NE: 'Neural and Evolutionary Computing',
    NA: 'Numerical Analysis',
    OS: 'Operating Systems',
    OH: 'Other',
    PF: 'Performance',
    PL: 'Programming Languages',
    RO: 'Robotics',
    SE: 'Software Engineering',
    SD: 'Sound',
    SC: 'Symbolic Computation'
  },
  nlin: {
    AO: 'Adaptation and Self-Organizing Systems',
    CG: 'Cellular Automata and Lattice Gases',
    CD: 'Chaotic Dynamics',
    SI: 'Exactly Solvable and Integrable Systems',
    PS: 'Pattern Formation and Solitons'
  },
  'cond-mat': {
    'dis-nn': 'Disordered Systems and Neural Networks',
    'mes-hall': 'Mesoscopic Systems and Quantum Hall Effect',
    'mtrl-sci': 'Materials Science',
    other: 'Other',
    soft: 'Soft Condensed Matter',
    'stat-mech': 'Statistical Mechanics',
    'str-el': 'Strongly Correlated Electrons',
    'supr-con': 'Superconductivity'
  },
  noPrefix: {
    'astro-ph': 'Astrophysics',
    'gr-qc': 'General Relativity and Quantum Cosmology',
    'hep-ex': 'High Energy Physics - Experiment',
    'hep-lat': 'High Energy Physics - Lattice',
    'hep-ph': 'High Energy Physics - Phenomenology',
    'hep-th': 'High Energy Physics - Theory',
    'math-ph': 'Mathematical Physics',
    'nucl-ex': 'Nuclear Experiment',
    'nucl-th': 'Nuclear Theory',
    'quant-ph': 'Quantum Physics'
  },
  'astro-ph': {
    GA: 'Astrophysics of Galaxies',
    CO: 'Cosmology and Nongalactic Astrophysics',
    EP: 'Earth and Planetary Astrophysics',
    HE: 'High Energy Astophysical Phenomena',
    IM: 'Instrumentation and Methods for Astrophysics',
    SR: 'Solar and Stellar Astrophysics'
  }
};
